### ISSUE TITLE
 Deformable mirror show up as unavailable after installing the Thorlabs_DM_Device_Adapter

### ISSUE THREAD

**Issue by DominikStich** [HohlbeinLab/Thorlabs_DM_Device_Adapter#1]
Hi,
I tried to install the Thorlabs_DM_Device_Adapter, but I couldn't get it to work with with the latest stable version of Micro-Manager (version MM 2.0.0) or the latest nightly build. 
The Thorlabs_Deformable_Mirror only shows up as "unavailable" in the hardware configuration wizzard after copying “mmgr_dal_Thorlab_Deformable_Mirror.dll”, “TLDFM_64.dll” and “TLDFMX_64.dll” into the Micro-Manager location. 
Is there anything that I am missing?
I would greatly appreciate your help!

**Comment by Abbas72** [comment]
Hi,
I built a new version with the updated package

Best,
Abbas.

**Comment by DominikStich** [comment]
Thank you so much!
